### ISSUE TITLE
can't exec "tobin" (build failure)

### ISSUE THREAD

**Issue by nikhiljha** [wav/nix-odroid-n2#2]
Building on x86_64 NixOS 20.03 (`nix-build release.nix -A sdImage`):

```
checking sys/ioctl.h usability... yes
./tobin
/nix/store/x7fr0bvnwvqvr3zg60di9jxvfwimcw7m-bash-4.4-p23/bin/bash: ./tobin: cannot execute binary file: Exec format error
make[1]: *** [Makefile:630: digiface_firmware.bin] Error 126
make[1]: Leaving directory '/build/alsa-firmware-1.2.1/hdsploader'
...
cannot build derivation '/nix/store/cgjbbaphm0kphfc3ls04ga65cqx96627-nixos-system-nixos-20.03.1942.6d68b920eb2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nrhx8hkmslbjdkv33q1divwlkqm52789-ext4-fs.img.zst-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xi3x8i014k91s7lilzwb1d7dza6w8i42-odroid-n2-20.03.1942.6d68b920eb2-aarch64-linux.img-aarch64-unknown-linux-gnu.drv': 1 dependencies couldn't be built
error: build of '/nix/store/xi3x8i014k91s7lilzwb1d7dza6w8i42-odroid-n2-20.03.1942.6d68b920eb2-aarch64-linux.img-aarch64-unknown-linux-gnu.drv' failed
```

Tried to extract the relevant parts of the log. The full log is so long that my usual paste service times out when I try to upload it :(

Seems like it's trying to exec an arm binary on x86_64?

**Comment by wav** [comment]
> Seems like it's trying to exec an arm binary on x86_64?

Yes, this is what I find sometimes when cross-compiling. I haven't done it for a while as I'm doing `arm64` builds now.

You may find it possible to build on Armbian with `nix` with some swap space enabled.

I've attached the current `arm64`  build. That may get you going.

**Comment by nikhiljha** [comment]
Thanks, looks like [the image you uploaded](https://github.com/wav/nix-odroid-n2/releases/tag/06052020) isn't publicly accessible though(?)

Might want to upload it in the `Attach binaries by dropping them here or selecting them.` section.

**Comment by wav** [comment]
I've added an attachment to the release.

**Comment by nikhiljha** [comment]
Yay! Booted just fine from eMMC. UART wasn't working for some reason, but networking was, so I plugged in a USB keyboard and (blindly) enabled SSH (`sudo systemctl enable sshd`).

Added [this config](https://nixos.wiki/wiki/NixOS_on_ARM#NixOS_installation_.26_configuration) and did a `nixos-rebuild switch` and now it doesn't boot 😆

How are you installing nixos? Would you mind sharing a basic version of your config?

---

Edit: I tried again with `nixos-generate-config`, followed by `nixos-rebuild dry-run`. It looks like it tries to replace the kernel. I'm not too familiar with nix but I'm pretty sure there's a way I can pin the kernel package, so I will try that before `nixos-rebuild switch`ing.

```
these paths will be fetched (74.53 MiB download, 144.23 MiB unpacked):
  /nix/store/1g8fpizqryfday6nsi73zwh4f1mm3c41-lndir-1.0.3
  /nix/store/34ddg5v0icrc7c5qj3zm69zygjqsxsai-extra-utils
  /nix/store/4jn4krysvqqm6jzy7j85lifbvhdah3lv-link-units
  /nix/store/5k646vdsv9hi0kdrwj8imhn4vz3m0w86-initrd-kmod-blacklist-ubuntu
  /nix/store/6np67b3c05fldh3ca5rlb0knsx77khv1-linux-5.4.35
  /nix/store/95jh4hwhzzq67x4d1l34flnxf57anprj-udev-rules
  /nix/store/9yz70v26idchs87mq7nfxb47hzxyigi8-nuke-references
  /nix/store/cddphssvafp8fd35nx4ydv41qp4z88fm-sudoers
  /nix/store/ddvrfcmi704s0ahp6qi91bym0avpdzy9-getconf-1003.1-2008
  /nix/store/gs5jlbxv4mndnk2sxmb5wil5ax3sjrm8-libxslt-1.1.34
  /nix/store/m9b26daw05ag17mkx6a50jsfnvbdj6rx-keymap
  /nix/store/phxspyfh81xpgsnmiy2dh6pxk6bxiblb-desktop-file-utils-0.24
  /nix/store/pz0mmj91yp38mm623xi3xz9ixcmd5fpx-sshd.conf-validated
  /nix/store/snrkzy462l6hgxbpwmzks12crxqmqzzn-cpupower-5.4.35
  /nix/store/xwh118my1j8005bl6zlfq7l2xswjy1wg-wget-1.20.3
  /nix/store/y433h8h7qr8dkm8gm1hn61vw9wl1s5mq-texinfo-6.5
  /nix/store/z2ikvkcyypk3s58fr0kh7fi45j0x9m6g-libxslt-1.1.34-bin
```

---

Edit 2: To resolve this, I did...

```bash
cd /etc/nixos
sudo git clone https://github.com/wav/nix-odroid-n2.git
sudo vim configuration.nix # add ./nix-odroid-n2/modules/profile.nix as an import
```

Thanks! :D
